"""migrate_midtrans_to_doku

Revision ID: 667ecbb432df
Revises: a1b2c3d4e5f6
Create Date: 2026-04-16 10:47:54.678720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667ecbb432df'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_transactions', sa.Column('payment_url', sa.String(length=255), nullable=True))
    op.drop_column('user_transactions', 'snap_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_transactions', sa.Column('snap_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user_transactions', 'payment_url')
    # ### end Alembic commands ###
