"""add order_id to transactions

Revision ID: 71e04c379055
Revises: 8c1b5bd8f9ca
Create Date: 2026-03-12 15:28:56.476122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e04c379055'
down_revision: Union[str, Sequence[str], None] = '8c1b5bd8f9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_transactions', sa.Column('order_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_user_transactions_order_id'), 'user_transactions', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_transactions_order_id'), table_name='user_transactions')
    op.drop_column('user_transactions', 'order_id')
    # ### end Alembic commands ###
