"""Add sub_category and AI fields

Revision ID: 732181cb877d
Revises: acb8fe3c661d
Create Date: 2026-03-16 10:24:03.511516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732181cb877d'
down_revision: Union[str, Sequence[str], None] = 'acb8fe3c661d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('ai_analysis', sa.JSON(), nullable=True))
    op.add_column('exam_sessions', sa.Column('ai_status', sa.String(length=20), server_default='none', nullable=False))
    op.add_column('questions', sa.Column('sub_category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'sub_category')
    op.drop_column('exam_sessions', 'ai_status')
    op.drop_column('exam_sessions', 'ai_analysis')
    # ### end Alembic commands ###
