"""add_question_id_and_indexes_to_chat_sessions

Revision ID: 74f6936054b3
Revises: 507cf747fdca
Create Date: 2026-03-19 15:28:36.384126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f6936054b3'
down_revision: Union[str, Sequence[str], None] = '507cf747fdca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_session_user_exam', 'chat_sessions', ['user_id', 'exam_session_id'], unique=False)
    op.create_index('ix_chat_session_user_question', 'chat_sessions', ['user_id', 'question_id'], unique=False)
    op.alter_column('feedbacks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('feedbacks', 'priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.create_index(op.f('ix_feedbacks_status'), 'feedbacks', ['status'], unique=False)
    op.create_unique_constraint('uq_package_question_number', 'questions', ['package_id', 'number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_package_question_number', 'questions', type_='unique')
    op.drop_index(op.f('ix_feedbacks_status'), table_name='feedbacks')
    op.alter_column('feedbacks', 'priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('feedbacks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('ix_chat_session_user_question', table_name='chat_sessions')
    op.drop_index('ix_chat_session_user_exam', table_name='chat_sessions')
    # ### end Alembic commands ###
