"""add_is_active_to_package

Revision ID: 79e0aa03dad6
Revises: 74f6936054b3
Create Date: 2026-03-19 17:44:42.560825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e0aa03dad6'
down_revision: Union[str, Sequence[str], None] = '74f6936054b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('packages', sa.Column('is_active', sa.Boolean(), nullable=True))
    # Update existing rows to True
    op.execute("UPDATE packages SET is_active = true")
    # Set to NOT NULL
    op.alter_column('packages', 'is_active', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'is_active')
    # ### end Alembic commands ###
