"""add pro account support

Revision ID: 8c1b5bd8f9ca
Revises: c0d8d1389655
Create Date: 2026-03-12 15:23:43.745411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1b5bd8f9ca'
down_revision: Union[str, Sequence[str], None] = 'c0d8d1389655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable first
    op.add_column('user_transactions', sa.Column('transaction_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('is_pro', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pro_expires_at', sa.DateTime(), nullable=True))

    # 2. Set default values for existing rows
    op.execute("UPDATE user_transactions SET transaction_type = 'single_package'")
    op.execute("UPDATE users SET is_pro = FALSE")

    # 3. Alter columns to be non-nullable
    op.alter_column('user_transactions', 'transaction_type', nullable=False)
    op.alter_column('users', 'is_pro', nullable=False)

    # 4. Alter package_id to be nullable
    op.alter_column('user_transactions', 'package_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pro_expires_at')
    op.drop_column('users', 'is_pro')
    op.alter_column('user_transactions', 'package_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('user_transactions', 'transaction_type')
    # ### end Alembic commands ###
