"""add is_preview flag to exam sessions

Revision ID: 998993f6b30a
Revises: 79e0aa03dad6
Create Date: 2026-03-21 19:42:08.487390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998993f6b30a'
down_revision: Union[str, Sequence[str], None] = '79e0aa03dad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('is_preview', sa.Boolean(), nullable=True))
    op.execute("UPDATE exam_sessions SET is_preview = false")
    op.alter_column('exam_sessions', 'is_preview', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_sessions', 'is_preview')
    # ### end Alembic commands ###
