"""Add score categories to ExamSession

Revision ID: 9bf0e9dc25dc
Revises: 9fd93fdf2063
Create Date: 2026-03-10 17:08:20.053364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf0e9dc25dc'
down_revision: Union[str, Sequence[str], None] = '9fd93fdf2063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('score_twk', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('exam_sessions', sa.Column('score_tiu', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('exam_sessions', sa.Column('score_tkp', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_sessions', 'score_tkp')
    op.drop_column('exam_sessions', 'score_tiu')
    op.drop_column('exam_sessions', 'score_twk')
    # ### end Alembic commands ###
