"""Refactor questions and options

Revision ID: 9fd93fdf2063
Revises: 0a4e9e6ca3e6
Create Date: 2026-03-10 15:18:05.095554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fd93fdf2063'
down_revision: Union[str, Sequence[str], None] = '0a4e9e6ca3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questions', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('questions', sa.Column('discussion', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('number', sa.Integer(), nullable=False))
    op.drop_column('questions', 'options')
    op.drop_column('questions', 'points')
    op.drop_column('questions', 'correct_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('correct_answer', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('questions', 'number')
    op.drop_column('questions', 'discussion')
    op.drop_column('questions', 'image_url')
    op.drop_table('question_options')
    # ### end Alembic commands ###
