"""add_option_id_to_answers

Revision ID: acb8fe3c661d
Revises: b1c89206603a
Create Date: 2026-03-16 09:56:49.424075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb8fe3c661d'
down_revision: Union[str, Sequence[str], None] = 'b1c89206603a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('option_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'answers', 'question_options', ['option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'option_id')
    # ### end Alembic commands ###
