"""Add donation fields to transactions

Revision ID: b1c89206603a
Revises: 62675d2262c7
Create Date: 2026-03-13 09:41:30.926201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c89206603a'
down_revision: Union[str, Sequence[str], None] = '62675d2262c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_transactions', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('user_transactions', sa.Column('is_anonymous', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_transactions', 'is_anonymous')
    op.drop_column('user_transactions', 'message')
    # ### end Alembic commands ###
