"""add is_passed to exam_sessions

Revision ID: c0d8d1389655
Revises: ab2bdde635a7
Create Date: 2026-03-11 22:21:55.906045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d8d1389655'
down_revision: Union[str, Sequence[str], None] = 'ab2bdde635a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('is_passed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_sessions', 'is_passed')
    # ### end Alembic commands ###
