"""Add weekly tryout fields to package

Revision ID: cbfce112e27f
Revises: 71e04c379055
Create Date: 2026-03-12 23:06:12.369761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfce112e27f'
down_revision: Union[str, Sequence[str], None] = '71e04c379055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('is_published', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('packages', sa.Column('is_weekly', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('packages', sa.Column('start_at', sa.DateTime(), nullable=True))
    op.add_column('packages', sa.Column('end_at', sa.DateTime(), nullable=True))
    op.add_column('question_options', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_options', 'image_url')
    op.drop_column('packages', 'end_at')
    op.drop_column('packages', 'start_at')
    op.drop_column('packages', 'is_weekly')
    op.drop_column('packages', 'is_published')
    # ### end Alembic commands ###
