"""add_feedback_table

Revision ID: f662bb24f8b4
Revises: 1869d61f37d7
Create Date: 2026-03-19 11:25:23.446284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f662bb24f8b4'
down_revision: Union[str, Sequence[str], None] = '1869d61f37d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.create_index(op.f('ix_answers_session_id'), 'answers', ['session_id'], unique=False)
    op.create_index('ix_exam_session_user_package', 'exam_sessions', ['user_id', 'package_id'], unique=False)
    op.create_index('ix_exam_session_user_status', 'exam_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_exam_sessions_package_id'), 'exam_sessions', ['package_id'], unique=False)
    op.create_index(op.f('ix_exam_sessions_status'), 'exam_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_exam_sessions_user_id'), 'exam_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_transactions_package_id'), 'user_transactions', ['package_id'], unique=False)
    op.create_index(op.f('ix_user_transactions_payment_status'), 'user_transactions', ['payment_status'], unique=False)
    op.create_index(op.f('ix_user_transactions_user_id'), 'user_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_transactions_user_id'), table_name='user_transactions')
    op.drop_index(op.f('ix_user_transactions_payment_status'), table_name='user_transactions')
    op.drop_index(op.f('ix_user_transactions_package_id'), table_name='user_transactions')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_exam_sessions_user_id'), table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_status'), table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_package_id'), table_name='exam_sessions')
    op.drop_index('ix_exam_session_user_status', table_name='exam_sessions')
    op.drop_index('ix_exam_session_user_package', table_name='exam_sessions')
    op.drop_index(op.f('ix_answers_session_id'), table_name='answers')
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
