name: Deploy CPNS Proyek

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/test-cpns
            
            # Memaksa server mengikuti kode terbaru dari GitHub
            git fetch origin main
            git reset --hard origin/main
            
            # Build ulang dengan argumen variabel environment
            # Build ulang dan nyalakan aplikasi
            # docker-compose akan otomatis membaca file .env di server
            docker compose up -d --build --remove-orphans

            # Menjalankan migrasi database agar tabel baru (Donation, dll) tercipta
            docker compose exec -T backend alembic upgrade head
            
            # Bersihkan sampah image agar hardisk Droplet tidak penuh
            docker image prune -f
